### ISSUE TITLE
Bumping version fails in CI

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#118]
**Goal**
fix version bumping issue
e.g., [Bump version - on: push (b168380)](https://github.com/Woile/commitizen/commit/b1683800d9d39f8df72fa6875e5d4c031ae83eba/checks?check_suite_id=396196645)

**Description**
I would purpose two solutions for this issue.

1. force conventional_commit cz to bump on every commit (even for doc, refactor, etc.)
2. add a function to check whether there is a version change since the last tagging

**Comment by Lee-W** [comment]
If we're to take the second approach, maybe we can add an `if not dry_run and new_version == current_version` to check whether the version is changed. If not, we can break here.
@Woile What do you think?

**Comment by Woile** [comment]
I haven't decided yet on this particular issue. I think is worth discussion in here, what do we want? So far I haven't faced any issue but the error in the "actions", so I've let it happen. I don't want to go one way, and later have a problem and realize the other way would make it simpler.

According to the [conventional commits ref](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#how-does-this-relate-to-semver) we are okayish (because we include `perf` and `refactor`).

Other tools like lerna, or conventional changelog [1](https://github.com/conventional-changelog/standard-version/issues/163) [2](https://github.com/lerna/lerna/issues/2379) [3](https://github.com/lerna/lerna/issues/1425) people complain of the increment when not feat, fix or breaking change

**Comment by Woile** [comment]
> If not, we can break here.

Would you break without an error code?

**Comment by Lee-W** [comment]
> what do we want?
A way to make CI pass. But after a second thought, I think to change the script in GitHub workflow might be a more reasonable solution for this issue. However, I would argue that making the `if not dry_run and new_version == current_version` change is still nice to have. Because it's an error we can detect earlier.

> Would you break without an error code?
I will break with an error code. We have a "NOTHING_TO_COMMIT" error, which is a similar case to this one. For consistency, I think it's better to have one.
Also, I found that error codes separate across files.
I think we can make the error codes a module like `commitizen/defaults.py`.

**Comment by Lee-W** [comment]
What about giving an argument for skipping when there is no tag to update without throwing an error?

**Comment by Lee-W** [comment]
Since you mention [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) spec, do you think we can add this tool to the [Tooling for Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#tooling-for-conventional-commits) section?

**Comment by Woile** [comment]
Late reply, feel free to send a PR to the Conventional Commmit section, that'd be great!

I'd leave it as is for now, or we could update [this line](https://github.com/commitizen-tools/commitizen/blob/master/.github/workflows/bumpversion.yml#L10) to be:

`if: "!startsWith(github.event.head_commit.message, 'bump:|docs:|ci:|')"` and the rest, but I'm not sure if it will work

**Comment by Lee-W** [comment]
I'm thinking of making it a different error code so that the user can choose to handle it or not. The next thing I will work on is #128 . I can handle it there. BTW, is there a difference between [NO_COMMITS_FOUND](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/error_codes.py#L9) and [NO_REVISION](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/error_codes.py#L28)

**Comment by Lee-W** [comment]
It seems to be solved. Let's close it
