### ISSUE TITLE
Use pypi api token instead of account/password

### ISSUE THREAD

**Issue by Lee-W** [commitizen-tools/commitizen#161]
@Woile We're currently using your pypi account/password for publishing commitizen to PyPI. [1] Do you think we should use API token instead to avoid exposing your credentials?

[1] https://github.com/commitizen-tools/commitizen/blob/master/scripts/publish#L2
[2] https://pypi.org/help/#apitoken
[3] https://github.com/pycontw/pycontw-postevent-report-generator/blob/master/.github/workflows/python-publish.yaml#L35

**Comment by Woile** [comment]
I'll take care soon, thanks Lee

**Comment by Lee-W** [comment]
I just update the documentation. 🙂 I'm considering [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) as a reference as well. It's not necessary for us since we're using poetry. But it could be a great option for those using setup.py However, I'm thinking of whether it will make the document too complicate to read. What do you think?

**Comment by Woile** [comment]
We can add a recommendation for the github action. 
But poetry and twine require one line to publish the package. And because username is the string "__token__" and the password (token) is set as a secret, there's not much complexity, is used as a normal upload.

What I actually noticed is that we should specify that the example is specifically for python.

**Comment by Lee-W** [comment]
The title of that section is "Publishing a python package". It seems to be clear for me.

**Comment by Woile** [comment]
Perfect, brain fart haha

**Comment by Woile** [comment]
we are now using `access_token` :tada:
