### ISSUE TITLE
[Bug] Commit subject should automatically be lowercase

### ISSUE THREAD

**Issue by alecgerona** [commitizen-tools/commitizen#239]
## Description
Commit subject is not forced to be lowercase

## Steps to reproduce
1. `cz c`
2. Choose any type.
3. Write an uppercase character in the subject.
4. Commit.

## Current behavior

It maintains the uppercase character. 

## Desired behavior
The commit subject should fully be lowercase. 

## Environment

- commitizen version: 1.23.0
- python version: 3.6.10
- operating system: Arch Linux

**Comment by Woile** [comment]
Hey unfortunately (for you haha) I truly believe this should not be enforced. 

The scope may refer to a class, you may want to upper case something, components in web design usually start with an upper case, and let's not start with languages that rely heavily in CamelCase.
The current conventional commits will be flexible in that regard.
If you really want to enforce it, you can create a different cz ruling based on the existing one, using [the template](https://github.com/commitizen-tools/commitizen_cz_template).
At the beginning of the project, I enforced it, and brought a lot of complications for me.

Some questions that come to my mind:
- Where does it say that it has to be lowercase? 
- Why should it be lower case? What are the benefits?

So far we use lower case, but if we were using upper case, the changelog items would begin with upper case, so that's a plus for upper case.

**Comment by Lee-W** [comment]
I don't think this should be enforced either. I think the reason for this issue might due to the fact that commitizen in java script does so. But we don't need to follow everything they implemented.

**Comment by alecgerona** [comment]
Yeah I'm using commitizen js and was used to the automatic lowercase since it does mention in the CLI that it should be lowercase so I thought this should be enforced.

**Comment by Woile** [comment]
We'll keep it as is for now. I'll close the ticket, but feel free to open it again if you want to discuss the topic more.
Regars!

**Comment by alecgerona** [comment]
@Woile how about lowercasing just the first character of the sentence?

**Comment by Woile** [comment]
I thought about that, but how would you deal with a commit like this?

```
feat: UserShop exposed as user_shop/ in endpoint
```

The moment you try to reference something in your source code, it won't match with your commit if it's converted to lowercase (`userShop` is not `UserShop`).

## Some alternatives
- create a pre-commit hook which lower cases the commit message (or checks it).
- create another `cz-conventional-commits-lower-case` which converts to lower case the message. It can extend the current one, in the message format call `super` and the result of that `.lower()` and that'd be it.

More ideas?

**Comment by alecgerona** [comment]
Personally, I wouldn't have this issue since I always start my commits with verbs or use the active voice, regardless of commit type. Given that, I'd like for it to be an option given the number of times I automatically capitalize the start of my sentences. I understand why you guys would not want it to be default.
