### ISSUE TITLE
Breaking change should support multiline

### ISSUE THREAD

**Issue by gsemet** [commitizen-tools/commitizen#346]
## Description
Breaking change only extract the first line. is it possible to extract the whole paragraph?

**Comment by Lee-W** [comment]
I'm afraid I do not quite understand your question. Could you please provide some examples?

**Comment by gsemet** [comment]
Let say I have this commit:

```
fea: this is a change on my project

BREAKING CHANGE: this is a breaking
change with description on multiple line

blablablabla
```

cz changelog only extract `this is a breaking` while the rest of the paragraph is ignored.

**Comment by Woile** [comment]
Hey, this would be a nice addition, the implementation it's a bit complex I think but we could give it a try. 

```
fea: this is a change on my project

BREAKING CHANGE: this is a breaking
change with description on multiple line

blablablabla
```

Just to be clear, from this example, we could take:
> BREAKING CHANGE: this is a breaking
change with description on multiple line

because blablabla would be considered as footer.

And also I don't think we could be able to support `!` it's a bit of a complex case.

**Comment by gsemet** [comment]
Agree. I do not use the ! syntax anyway. pretty ugly
