### ISSUE TITLE
[python] Invalid pre-commit execution with commitizen-emoji

### ISSUE THREAD

**Issue by jrnp97** [commitizen-tools/commitizen#437]
## Description
Pre-commit validation fails when using the third-party template [commitizen-emoji](https://commitizen-tools.github.io/commitizen/third-party-commitizen/#commitizen-emoji)

third-party inclusion: https://github.com/commitizen-tools/commitizen/pull/217

## Steps to reproduce
1. Install commitizen in the project [docs](https://commitizen-tools.github.io/commitizen/#installation)
2. Install third-party library [docs](https://github.com/commitizen-tools/commitizen/blob/master/docs/third-party-commitizen.md#commitizen-emoji)
3. Config pre-commit.
4. Try to do a commit :)

## Current behavior
Pre-commit validation fails.

## Desired behavior
Pre-commit validation pass.

**Screenshots**
error:
![image](https://user-images.githubusercontent.com/26009859/135250667-1a3f305c-45e1-4816-b875-7e7324f38a57.png)

config [pyproject.toml]:
![image](https://user-images.githubusercontent.com/26009859/135250929-1c5e7ebe-a1d6-4b3b-bc37-d64f9b3b11b0.png)

pre-commit config:
![image](https://user-images.githubusercontent.com/26009859/135251155-aaf8916a-5100-4666-98e7-b0f795a79e00.png)

## Environment
```bash
$ cz version --report
# output
Commitizen Version: 2.19.0
Python Version: 3.8.5 (default, Sep 10 2020, 16:58:22)
[GCC 8.3.0]
Operating System: Linux
```

**Comment by Lee-W** [comment]
Hi, I think the problem is that `cz_commitizen_emoji` did not implement schema_pattern ([example on conventional commit](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/cz/conventional_commits/conventional_commits.py#L191)) so that [check](https://github.com/commitizen-tools/commitizen/blob/master/commitizen/commands/check.py#L59) could not work. I suggest you create an issue on [cz_commitizen_emoji](https://github.com/marcelomaia/commitizen-emoji) or send a PR to them. Thanks!
