### ISSUE TITLE
Check for Commitizen Commit in a List of Commits

### ISSUE THREAD

**Issue by courtneysprouse** [commitizen-tools/commitizen#617]
### Description

I'm not sure if this is existing functionality and I missed it. But I thought it would put it here just in case. I love the `cz check` feature but I wish instead of checking if all commits are in commitizen format, I could just check if one of the commits was a cz commit and in the correct format. So I could write a conditional like this `if cz-commit in commits` for my pipeline.

**Comment by Lee-W** [comment]
Could you please try `cz check --rev-range <rev1>..<rev2>` e.g., `cz check --rev-range main..HEAD`

**Comment by Lee-W** [comment]
I'll close it for now. But feel free to reopen it if my answer is not what you want

**Comment by courtneysprouse** [comment]
Hi! Thanks for answering! This actually doesn't work unless you use cz to make all the commits. It's nice to be able to do commits with git, while still making sure cz commits are valid. Does that make sense?

**Comment by Lee-W** [comment]
@courtneysprouse I think we can use `git` to do commit and use `cz` to check. Could you please share the commands that doesn't work?

**Comment by Lee-W** [comment]
@courtneysprouse Hi, sorry for late reply. I get your idea, but I don't think that what commitizen wants to do. IMO, commitizen checks all the git commits instead of the ones just created by commieizen. One workaround is customized your commit rule to embed something like `created from commitizen` to your message and create a customized checker so that other commits will be ignored
