### ISSUE TITLE
Is there any way to use this in a prepare-commit-msg hook?

### ISSUE THREAD

**Issue by ArgentumCation** [commitizen-tools/commitizen#689]
### Description

The Node version of commitizen provides a `--hook` flag that allows users to generate a commit message, without actually performing a commit, is there a way to replicate this behavior in the Python version?

The example `prepare-commit-hook` in the cz-cli documentation is something like this:
```bash
#!/bin/bash
exec < /dev/tty && node_modules/.bin/cz --hook || true
```

### Possible Solution

A new command or flag such as `cz message` or `cz commit --message-only` that could be embedded into a git hook that would generate a commit message without performing a full commit.

### Additional context

Since the commit message in `cz --dry-run` is output to stdout (along with the questions) there's no way to just pipe the output of that directly into `.git/COMMIT_MSG`

**Comment by woile** [comment]
I'm ok with this feature. The question is, should we refactor `--dry-run` or should we introduce another flag?
In case we go for `--dry-run` how could we refactor it? Sending the questionary to the stderr?

**Comment by crai0** [comment]
I think keeping `--dry-run` the way it is makes more sense because users probably use it to test their customizations. I would like to see something similar to what @ArgentumCation proposed:

The `commit` sub-command has a new `--prepare-message` option that takes a file path. When the flag is passed, commitizen runs the usual interactive dialog for preparing the commit message  and then writes the final message to the specified file without performing a commit.

This way people can use it for more than just `prepare-commit-msg` hooks but it also flows well with how pre-commit handles these kinds of hooks https://pre-commit.com/#prepare-commit-msg, so going with this proposal would also make adding a new `prepare-commit-msg` pre-commit hook straightforward.

I could try wipping up a prototype for this if that helps.

**Comment by woile** [comment]
Sounds good, PR is welcome.

**Comment by crai0** [comment]
I did some research and interactive pre-commit hooks are not a thing https://github.com/pre-commit/pre-commit/issues/1857.

A working `prepare-commit-msg` hook (not using pre-commit) could look like this:

```bash
#!/bin/sh
COMMIT_MSG_FILE=$1
exec < /dev/tty && cz commit --dry-run --write-message-to-file $COMMIT_MSG_FILE || true
```

I'll add a tutorial to the docs as well.

**Comment by crai0** [comment]
I opened a pull request. Would be awesome to see this getting released soon.
