### ISSUE TITLE
Specify build metadata in tags

### ISSUE THREAD

**Issue by xeor** [commitizen-tools/commitizen#945]
### Description

https://github.com/commitizen-tools/commitizen/issues/436 describes most of what I need, but it is closed.

The gist is that semver supports additional build metadata at the end of the version after a `+` sign.
It states that the data behind the `+` should not be considered part of the version when doing version calculation, only as information.

Some times, I need to put additional labels on a tag, like `1.2.3+label1.label2.label3`. Or maybe someone wants a commit hash in there (as other issues has stated as well).

### Possible Solution

Using this field in tag_format is possible, but I suggest there is a way to override the whole field from cli. Example

`cz bump --build-metadata=label1.label2.label3`

could produce a bumped version, with the labels above.

### Additional context

The build-metadata in my case needs to come from the context of where the cli runs. It needs to be static, or scriptable, not from a set of variables like $commithash, $buildhost.

If this feature request looks fine, I will try to get a PR ready for it, but I would like if it will be accepted first :)

**Comment by woile** [comment]
Sounds like an interesting feature, I think it would be useful. Could you clarify whether you need only the tag to carry metadata or also the final version? Let's say you have a python application with its version, shouldn't that also reflect the version with the metadata?

Maybe we should have a mechanism to provide variables, that could be used to customize *both* the tag and the version itself.
Like `--build-metadata="HASH:abcde --build-metadata="HOST:abcde"`

Thoughts on this @Lee-W @noirbizarre ?

**Comment by noirbizarre** [comment]
Yes, I know this mechanism. It is incredibly useful, I've been using for years, mostly to track CI/CD deployment.

It exists in both SemVer (build identifier) and PEP440 (local build identifier) with the same rules that you should be aware of:
- to install this kind of version, you need to know the exact version because they are not eligible to update (`1.2.3+abcd` won't be installed by your package manager if to update if your package is `1.2.2`) because the `+part` is not sortable
- but some tools have issue with it (helm sees it as an update) so you need to be careful

We never tag those release, they are meant to exist between formal tags (but I could understand a use case where you tag them too).

Here's the use case I had to illustrate:
- deploying (and tracking) all builds: version `x.y.z+<commitish>.<buildno>`
- deploying (and tracking) feature branch builds: version `x.y.z+<branch slug>.<commitish>,<buildno>`

And there is one few people are aware of: the `scm` provider (which I currently used on all my projects). It is already using this pattern.
With the `scm` provider (works the same for `setuptools`, `poetry` or `pdm`), either you are building a tag and the provider is injecting the tag as your version, either you are not and `scm` provider is injecting `<last tag>+<commitish>` and if you are on a dirty working copy, it injects ``<last tag>+<commitish>+<hash of changed files>`.

Note that some use `0.0.0+<metadata>` instead of `x.y.z+<metadata>` (I think with helm you don't have a choice)

So yes, this is a yes for me, but:
- we need to be clear on the scope and supported use cases
- we should look into `scm` providers to be as compliant with them as possible (I think)
- there are at least 2 different cases: just version injection or version bump

I would go for this syntax `--build-metadata=<free-form-metadata>` and make `commitizen` just validate the metadata according to the version schema used. The parameter can be used multiple times and order matters as they should be serialized in the same order to be deterministic. This would also allow supporting versioning schema using other delimiters than `+` and `.`

Ideally, it would be possible to bump without tagging in git (and without committing). In the continuous deployment case, you don't want a git tag by deployment, you just want the resulting package to carry this metadata, and ideally to have the matching changelog. So maybe we should add a `--no-tag` or `--read-only` flag for this (this was we support both case, formal tagging or just packaging metadata)

I don't think it is necessary for commitizen to provide placeholders like `$host` because they are specific to the use case. I can't however see a special marker `$commitish` (maybe more if we try to have parity with `scm` providers, the only part which can be handled by `commitizen`).

**Comment by xeor** [comment]
Thanks for the comments @noirbizarre, I implemented the basic idea in a PR. It works fine, would love for you to take a look.
